default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  database: lgelmash

development:
  <<: *default
  username: root
  password: root

production:
  <<: *default
  username: root
  password: PPbH%NeQ2.acqd
