default: &default
  adapter: mysql2
  encoding: utf8
  charset: utf8
  collation: utf8_general_ci
  pool: 5
  host: 127.0.0.1

development:
  <<: *default
  database: lgelmash_devel
  username: root
  password: root

test:
  <<: *default
  database: lgelmash_test
  username: root
  password: root

production:
  <<: *default
  database: lgelmash
  username: root
  password: 19uc[V2YV^56XE
